name: ci-cd

on:
  push:
    branches: [ main, develop, release]
  pull_request:
    branches: [ main, develop, release]

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GitHub repository URL
        run: echo "REPOSITORY_URL=https://github.com/CauaConceicao20/CalculadoraProjeto" >> $GITHUB_ENV

      - name: Validate commits
        run: |
          commit_message=$(git log -1 --pretty=format:"%s" HEAD)
          if [[ ! $commit_message =~ ((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*) && ! $commit_message =~ ^Merge ]]; then
            echo "commit is not valid: '$commit_message'"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: preflight

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package
        working-directory: calculadora

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      
      - name: Run Tests and Generate JaCoCo Report
        run: mvn test jacoco:report
        working-directory: calculadora

      - name: Archive JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: calculadora/target/site/jacoco/

  sonarCloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=CauaConceicao20_CalculadoraProjeto -Dsonar.organization=caua-conceicao -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: calculadora

  release:
    runs-on: ubuntu-latest
    needs: sonarCloud
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Run Integration Tests
        run: mvn integration-test
        working-directory: calculadora

      - name: Download JaCoCo Report
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report
          path: calculadora/target/site/jacoco

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Send JaCoCo Report to FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          FTPHOST = joaobsjunior.com.br
          JACOCO_REPORT="JacocoReport__$(date '+%F__%H-%M-%S')"
          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "
          mirror -R calculadora/target/site/jacoco /CalculadoraProjeto;
          quit"
          echo "# Link Jacoco report" >> $GITHUB_STEP_SUMMARY
          echo "https://$FTPHOST/projeto-a3/CalculadoraProjeto/$JACOCO_REPORT/" >> $GITHUB_STEP_SUMMARY

  versioning:
    runs-on: ubuntu-latest
    needs : test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set NPM token
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Semantic Release Changelog Plugin
        run: npm install @semantic-release/changelog

      - name: Install Semantic Release Git Plugin
        run: npm install @semantic-release/git

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        run: npx semantic-release

